name: Action CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Update Mappings
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: Infisical/secrets-action@v1.0.7
        with:
          method: "oidc"
          env-slug: "dev"
          project-slug: "github-g0zh"
          identity-id: "1ffe6b17-29ef-47ed-a54c-0912bbe40542"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{env.NGLBOT}}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Update Mappings
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[skip ci] Update mappings'
          file_pattern: 'dist/*.js dist/*.js.map dist/*.cjs'
          commit_user_name: nglbot
          commit_user_email: ghbot@nordicgamelab.org
          commit_author: nglbot <ghbot@nordicgamelab.org>
